### ISSUE TITLE
Add more options for pagination / infinite scroll for rendered websites

### ISSUE THREAD

**Issue by jakopako** [jakopako/goskyr#144]
There should be an option to click a button or trigger scrolling to load the next page of items on a webpage. Right now goskyr can only scrape links that point to the next page.

**Comment by jakopako** [comment]
Some examples where this would be useful: the Arena Wien website (https://arena.wien/Home/Programm#data_abonnement=-1&data_month=-1&data_year=-1&data_event_category=-1&searchTerm=&data_mode=DATE&data_pagenumber=0&page_header=alle+Monate) and the XTRA website (https://www.x-tra.ch/de/agenda/) Both are already being scraped for croncert.ch but only a limited number of concerts due to said limitation

**Comment by MarkJaroski** [comment]
Another example: https://www.cafeoto.co.uk/events/

**Comment by jakopako** [comment]
Another example that is currently not handled well.

https://www.30cc.be/nl/programma?seizoen=2022-2023&discipline=3

**Comment by jakopako** [comment]
another example https://palpfestival.ch/en/line-up/

**Comment by jakopako** [comment]
https://kantine.com/orte/kantine/

**Comment by jakopako** [comment]
yet another example: https://www.kulturmarkt.ch/veranstaltungen/

**Comment by jakopako** [comment]
With pr #222 clicking on 'load more' buttons and clicking through pages even with js rendering is now supported. Other things like for instance scrolling will be addressed in separate issues / PRs.
