### ISSUE TITLE
[Question] how to authenticate to websites

### ISSUE THREAD

**Issue by MushiTheMoshi** [jakopako/goskyr#148]
Hi there,

How can I use on sites that require authentication?

Regards,
Julio

**Comment by jakopako** [comment]
Hi 👋

thanks for your question. Unfortunately it’s currently not possible to authenticate to websites with goskyr. What kind of auth would you need? 

If you want to extend goskyr feel free to fork the repository and do a pull request. I can also try to look into this. Could you give me an example of a website that requires authentication and that you’d like to scrape?

Cheers, Jakob

**Comment by MushiTheMoshi** [comment]
Hi I have an SPA made with VUE which uses CSFR and COOKIES to do authentication, wondering if I would be able to do testings using this tool. 

This require login via web and follow steps to authenticate using AUTH0.

Regards,
Julio

**Comment by jakopako** [comment]
I was hoping for simple basic auth or tokens :D I'm afraid that I currently don't have the resources to look into this. Obviously, if you want to take a shot at it feel free! Otherwise I'm going to close this issue for now.

Cheers, Jakob
