### ISSUE TITLE
Support times with only the hour part

### ISSUE THREAD

**Issue by MarkJaroski** [jakopako/goskyr#168]
Maybe there's already a way to do this with regex, but so far at least I haven't found it in the main config.

One of the venues I'm working on lists time on the hour without the minute part. They do it French style, so it should be 21h00, but they just use 21h. To be clear if it's at 21:30 they will write 21h30, but for a concert at 21:00 they just write 21h.

Is this already possible somehow?

**Comment by jakopako** [comment]
This should be possible by defining two different layouts in the layout list. You can find an example here: https://github.com/jakopako/croncert-config/blob/main/croncert-config.yml#L89

Does this solve the issue?

**Comment by MarkJaroski** [comment]
Indeed it does!
