### ISSUE TITLE
Add debug flag

### ISSUE THREAD

**Issue by jakopako** [jakopako/goskyr#218]
debug output should among others show the http request and response (only headers?)

**Comment by MarkJaroski** [comment]
I'd like to be able to output the DOM, as seen by goquery. I've seen a couple of cases where the post js redered DOM appears to be different from what I see in the browser.

**Comment by jakopako** [comment]
Good point! I've had such cases too. Modified the source code temporarily to print the DOM which is of course ugly 😅 We'll have to think about how to do this exactly. In my experience the DOM often is way too big to print it to logs in an appealing way. Maybe write it to a file instead..

**Comment by jakopako** [comment]
Side note: I didn't have much time lately to work on this project. I'm hoping it'll get better but not sure 🤞

**Comment by MarkJaroski** [comment]
> Good point! I've had such cases too. Modified the source code temporarily to print the DOM which is of course ugly 😅 We'll have to think about how to do this exactly. In my experience the DOM often is way too big to print it to logs in an appealing way. Maybe write it to a file instead..

Dumping it to an html file is probably the best.

**Comment by MarkJaroski** [comment]
> Side note: I didn't have much time lately to work on this project. I'm hoping it'll get better but not sure 🤞

Don't worry about it at all. I completely understand. It's going to be like that for me the rest of the month and most of May.

**Comment by jakopako** [comment]
Added a few basic debugging logs. If the need arises, I'll add more. Moreover, if the `-debug` flag is set all html docs are written to files for inspection.
