### ISSUE TITLE
date string 'streda 17.05.2023 @20:00' not parsed correctly

### ISSUE THREAD

**Issue by jakopako** [jakopako/goskyr#221]
extend algorithm that derives date format from date strings accordingly. Website that contains those dates http://www.majestic.sk/program

At least 2 things do not work properly:
1. language is not yet supported
2. time string is not properly formatted

**Comment by jakopako** [comment]
For the language support first we need to add support to goodsign/monday.

**Comment by gedw99** [comment]
https://github.com/DustinJSilk/dinero.go might be useful for both backend and frontend.

**Comment by gedw99** [comment]
> goodsign/monday

 https://github.com/goodsign/monday looks good !

**Comment by jakopako** [comment]
Language seems to be supported by goodsign/monday now, see https://github.com/goodsign/monday/blob/master/format_sk_sk.go

**Comment by jakopako** [comment]
https://github.com/goodsign/monday/issues/67

**Comment by jakopako** [comment]
New version released
