### ISSUE TITLE
go install github.com/jakopako/goskyr@latest doesn't work and breaks at golearn/knn installation

### ISSUE THREAD

**Issue by alucab** [jakopako/goskyr#243]
I tried to install goskyr (I like the concept of this project and I want to learn a bit of go) and it fails

go: downloading github.com/jakopako/goskyr v0.5.7
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/PuerkitoBio/goquery v1.8.1
go: downloading github.com/antchfx/jsonquery v1.3.3
go: downloading github.com/goodsign/monday v1.0.1
go: downloading github.com/ilyakaznacheev/cleanenv v1.5.0
go: downloading golang.org/x/net v0.17.0
go: downloading github.com/agnivade/levenshtein v1.1.1
go: downloading github.com/gdamore/tcell/v2 v2.6.0
go: downloading github.com/rivo/tview v0.0.0-20220916081518-2e69b7385a37
go: downloading github.com/sjwhitworth/golearn v0.0.0-20221228163002-74ae077eafb2
go: downloading github.com/chromedp/cdproto v0.0.0-20231011050154-1d073bb38998
go: downloading github.com/chromedp/chromedp v0.9.3
go: downloading golang.org/x/exp v0.0.0-20230304125523-9ff063c70017
go: downloading github.com/BurntSushi/toml v1.2.1
go: downloading github.com/joho/godotenv v1.5.1
go: downloading olympos.io/encoding/edn v0.0.0-20201019073823-d3554ca0b0a3
go: downloading github.com/antchfx/xpath v1.2.3
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
go: downloading github.com/gdamore/encoding v1.0.0
go: downloading github.com/lucasb-eyer/go-colorful v1.2.0
go: downloading github.com/mattn/go-runewidth v0.0.14
go: downloading golang.org/x/term v0.13.0
go: downloading golang.org/x/text v0.13.0
go: downloading github.com/rivo/uniseg v0.4.3
go: downloading github.com/gobwas/ws v1.3.0
go: downloading golang.org/x/sys v0.13.0
go: downloading gonum.org/v1/gonum v0.12.0
go: downloading github.com/rocketlaunchr/dataframe-go v0.0.0-20201007021539-67b046771f0b
go: downloading github.com/gonum/matrix v0.0.0-20181209220409-c518dec07be9
go: downloading github.com/gonum/lapack v0.0.0-20181123203213-e4cdc5a0bff9
go: downloading golang.org/x/sync v0.1.0
go: downloading github.com/olekukonko/tablewriter v0.0.4
go: downloading github.com/google/go-cmp v0.5.8
go: downloading github.com/guptarohit/asciigraph v0.5.1
go: downloading github.com/gonum/blas v0.0.0-20181208220705-f22b278b28ac
# github.com/sjwhitworth/golearn/knn
go\pkg\mod\github.com\sjwhitworth\golearn@v0.0.0-20221228163002-74ae077eafb2\knn\knn.go:132:16: KNN.optimisedEuclideanPredict undefined (type *KNNClassifier has no field or method optimisedEuclideanPredict)

looking around I found this issue about the need of CGO

https://github.com/sjwhitworth/golearn/issues/286

**Comment by jakopako** [comment]
If you want to install it like this, you need a c compiler on your system. I think then your issue should be solved. I'll make this more clear in the readme, thanks for pointing this out. Alternatively, you can install goskyr in a different way, eg by downloading the correct binary from the releases page, see https://github.com/jakopako/goskyr/releases

**Comment by alucab** [comment]
yes i downloaded the binary and it works.
