### ISSUE TITLE
Add an event image field to the scraper.

### ISSUE THREAD

**Issue by MarkJaroski** [jakopako/goskyr#254]

**Comment by jakopako** [comment]
Hey Mark, is this about the discussion we had on adding image uri's to the event api and the scraper config?

**Comment by jakopako** [comment]
Is it ok if I close this issue? The scraper itself should be able to support a new field of type url. 

I made a new issue in the event-api repo, see https://github.com/jakopako/event-api/issues/29

**Comment by MarkJaroski** [comment]
Yes. Of course!
